version: '3.8'

services:
  patienthero:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: patienthero
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    tty: true
    stdin_open: true
    working_dir: /app
